### ISSUE TITLE
Download link broken in README.md

### ISSUE THREAD

**Issue by mikimn** [UKPLab/acl2020-confidence-regularization#1]
The first download link, namely [this](https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FMNLI.zip?alt=media&token=50329ea1-e339-40e2-809c-10c40afff3ce), is broken (Gives a permission denied). Is there another source to download the dataset from?

**Comment by mikimn** [comment]
Might be better to replace with the original GLUE benchmark link: https://gluebenchmark.com/tasks

**Comment by putama** [comment]
Hi, thanks for pointing that out! It's now been fixed and pointing to the GLUE page.
